### ISSUE TITLE
Error with code

### ISSUE THREAD

**Issue by CoderCentral100** [jpospychala/code_tetris#1]
Expected an identifier and instead saw '<' 
Expected an operator and instead saw '!' 
Expected a assignment or a function call and instead saw an expression
Missing Semicolon.
Missing Semicolon. (Another one) Unrecoverable syntax error. (0% scanned) @jpospychala

**Comment by jpospychala** [comment]
Hi,
thank you for rising the issue, unfortunately there's not enough details to resolve this issue.
